version: '3.1'

services:

  db:
    image: mysql:5
    container_name: mysql-server
    restart: unless-stopped
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.log:/var/log/mysql/mysql.log
    environment:
      MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
      #MYSQL_DATABASE: databasename
      #MYSQL_USER: dbusername
      #MYSQL_PASSWORD: dbuserpassword
    ports:
      - $MYSQL_PORT:3306  # expose container's port 3306 on host's port 33060

  web:
    image: apachephp  # Crea una nuova image a partire da php:apache
    #dockerfile: ./Dockerfile
    build: .
    container_name: web-server
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./www:/var/www/html
    ports:
      - $HTTP_PORT:80  # expose container's port 80 on host's port 8080, the web service

