version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-server
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.log:/var/log/mysql/mysql.log
    #command: tail -f /var/log/mysql/mysql.log
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: databasename
      #MYSQL_USER: dbusername
      #MYSQL_PASSWORD: dbuserpassword
    ports:
      - 3306:3306  # expose container's 3306 on host's 33060

  web:
    #image: php:apache
    #dockerfile: ./Dockerfile
    image: apachephp  # Crea una nuova image a partire da php:apache
    build: .
    container_name: web-server
    restart: always
    links:
      - db
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80  # expose container's 80 on host's 8080, the web service
      #- 4430:443  # expose container's 443 on host's 4433, the web service


#volumes:
#  dbdata

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

# vim: set tabstop=2 expandtab syntax on :
